class Job {
  final String id;
  final String? employerId;
  final String title;
  final String category;
  final String description;
  final double wage;
  final double? originalWage;
  final String status; // 'open', 'assigned', 'completed'
  final double rating;
  final int reviewCount;
  final String location;
  final String date;
  final String employerName;
  final String? workerName;
  final String? imageUrl;
  final bool verified;
  final bool urgent;

  const Job({
    required this.id,
    this.employerId,
    required this.title,
    required this.category,
    required this.description,
    required this.wage,
    this.originalWage,
    required this.status,
    required this.rating,
    required this.reviewCount,
    required this.location,
    required this.date,
    required this.employerName,
    this.workerName,
    this.imageUrl,
    this.verified = true,
    this.urgent = false,
  });

  factory Job.fromJson(Map<String, dynamic> json) {
    return Job(
      id: json['id']?.toString() ?? '',
      employerId: json['employer_id']?.toString(),
      title: json['title'] ?? '',
      category: json['category'] ?? 'General',
      description: json['description'] ?? '',
      wage: (json['price'] as num?)?.toDouble() ?? 0.0,
      originalWage: (json['original_price'] as num?)?.toDouble(),
      status: json['status'] ?? 'open',
      rating: (json['rating'] as num?)?.toDouble() ?? 5.0,
      reviewCount: (json['review_count'] as num?)?.toInt() ?? 0,
      location: json['location'] ?? 'Indiranagar',
      date: json['date'] ?? 'Today',
      employerName: json['employer_name'] ?? 'Employer',
      workerName: json['worker_name'],
      imageUrl: json['image_url'],
      verified: json['verified'] ?? true,
      urgent: json['urgent'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      if (id.isNotEmpty && !id.startsWith('job-')) 'id': id,
      if (employerId != null) 'employer_id': employerId,
      'title': title,
      'category': category,
      'description': description,
      'price': wage,
      if (originalWage != null) 'original_price': originalWage,
      'status': status,
      'rating': rating,
      'review_count': reviewCount,
      'location': location,
      'date': date,
      'employer_name': employerName,
      if (workerName != null) 'worker_name': workerName,
      if (imageUrl != null) 'image_url': imageUrl,
      'verified': verified,
      'urgent': urgent,
    };
  }

  Job copyWith({
    String? id,
    String? employerId,
    String? title,
    String? category,
    String? description,
    double? wage,
    double? originalWage,
    String? status,
    double? rating,
    int? reviewCount,
    String? location,
    String? date,
    String? employerName,
    String? workerName,
    String? imageUrl,
    bool? verified,
    bool? urgent,
  }) {
    return Job(
      id: id ?? this.id,
      employerId: employerId ?? this.employerId,
      title: title ?? this.title,
      category: category ?? this.category,
      description: description ?? this.description,
      wage: wage ?? this.wage,
      originalWage: originalWage ?? this.originalWage,
      status: status ?? this.status,
      rating: rating ?? this.rating,
      reviewCount: reviewCount ?? this.reviewCount,
      location: location ?? this.location,
      date: date ?? this.date,
      employerName: employerName ?? this.employerName,
      workerName: workerName ?? this.workerName,
      imageUrl: imageUrl ?? this.imageUrl,
      verified: verified ?? this.verified,
      urgent: urgent ?? this.urgent,
    );
  }
}

final List<Job> mockJobs = [
  // --- PAINTING ---
  const Job(
    id: 'job-1',
    title: 'Full House Painting (Interior Walls)',
    category: 'Painting',
    description: '3 BHK apartment interior wall painting & primer coat. Paints provided on site.',
    wage: 1500,
    originalWage: 1800,
    status: 'open',
    rating: 4.8,
    reviewCount: 24,
    location: 'Indiranagar, Stage 2',
    date: 'Today 14:00',
    employerName: 'Sharma Household',
    verified: true,
    urgent: true,
  ),
  const Job(
    id: 'job- painting-2',
    title: 'Exterior Waterproof Texture Painting',
    category: 'Painting',
    description: 'Weatherproof exterior wall coating for 2-storey bungalow facade.',
    wage: 2200,
    originalWage: 2500,
    status: 'open',
    rating: 4.9,
    reviewCount: 15,
    location: 'Koramangala, 5th Block',
    date: 'Tomorrow 10:00',
    employerName: 'Reddy Residences',
    verified: true,
  ),
  const Job(
    id: 'job-painting-3',
    title: 'Wooden Door & Window Polish Touchup',
    category: 'Painting',
    description: 'PU varnish polish touchup for 6 teakwood doors and window frames.',
    wage: 1100,
    status: 'open',
    rating: 4.6,
    reviewCount: 12,
    location: 'HSR Layout, Sector 1',
    date: 'Aug 5, 11:00',
    employerName: 'Anand Villa',
    verified: true,
  ),

  // --- CLEANING ---
  const Job(
    id: 'job-2',
    title: 'Deep Kitchen & Chimney Cleaning',
    category: 'Cleaning',
    description: 'Degreasing chimney filters, exhaust fan cleaning, and marble countertop scrub.',
    wage: 900,
    originalWage: 1200,
    status: 'open',
    rating: 4.9,
    reviewCount: 42,
    location: 'Koramangala, Block 4',
    date: 'Tomorrow 09:00',
    employerName: 'Verma Residences',
    verified: true,
  ),
  const Job(
    id: 'job-cleaning-2',
    title: 'Full Apartment Move-In Deep Scrub',
    category: 'Cleaning',
    description: 'Sanitizing bathrooms, windows, balcony scrub, and floor machine buffing.',
    wage: 1800,
    originalWage: 2100,
    status: 'open',
    rating: 4.8,
    reviewCount: 30,
    location: 'Indiranagar, 100ft Road',
    date: 'Today 16:00',
    employerName: 'Nair Household',
    verified: true,
    urgent: true,
  ),
  const Job(
    id: 'job-cleaning-3',
    title: 'Sofa & Carpet Steam Shampooing',
    category: 'Cleaning',
    description: 'Deep fabric extraction shampoo for 5-seater L-shape sofa and living room rug.',
    wage: 1250,
    status: 'open',
    rating: 4.7,
    reviewCount: 19,
    location: 'Whitefield, Main Road',
    date: 'Aug 4, 15:00',
    employerName: 'Deshmukh Apartments',
    verified: true,
  ),

  // --- PLUMBING ---
  const Job(
    id: 'job-3',
    title: 'Emergency Bathroom Pipe Leak Repair',
    category: 'Plumbing',
    description: 'Replacing broken PVC joint under sink & sealing shower drain leakage.',
    wage: 750,
    originalWage: 850,
    status: 'assigned',
    rating: 4.7,
    reviewCount: 18,
    location: 'HSR Layout, Sector 3',
    date: 'Today 16:30',
    employerName: 'Kapoor Villa',
    workerName: 'Ramesh Kumar',
    verified: true,
    urgent: true,
  ),
  const Job(
    id: 'job-plumbing-2',
    title: 'Overhead Tank Cleaning & Valve Fitting',
    category: 'Plumbing',
    description: '1000L PVC water tank vacuum cleaning and replacing main line ball valve.',
    wage: 950,
    status: 'open',
    rating: 4.9,
    reviewCount: 27,
    location: 'Jayanagar, 3rd Block',
    date: 'Tomorrow 08:30',
    employerName: 'Gowda Residency',
    verified: true,
  ),
  const Job(
    id: 'job-plumbing-3',
    title: 'Full Bathroom Sanitaryware Installation',
    category: 'Plumbing',
    description: 'Installing wall-hung closet, vanity basin mixer, and concealed diverter set.',
    wage: 2100,
    originalWage: 2400,
    status: 'open',
    rating: 4.8,
    reviewCount: 33,
    location: 'Bellandur, Outer Ring Rd',
    date: 'Aug 6, 10:00',
    employerName: 'Rao Penthouse',
    verified: true,
  ),

  // --- COOKING ---
  const Job(
    id: 'job-cooking-1',
    title: 'North & South Indian Daily Meal Cook',
    category: 'Cooking',
    description: 'Preparing breakfast and dinner for family of 4. Roti, curry, rice & dal.',
    wage: 800,
    status: 'open',
    rating: 4.9,
    reviewCount: 51,
    location: 'Indiranagar, 12th Main',
    date: 'Today 17:00',
    employerName: 'Bhasin Family',
    verified: true,
    urgent: true,
  ),
  const Job(
    id: 'job-cooking-2',
    title: 'Weekend Party Caterer & Live Tandoor',
    category: 'Cooking',
    description: 'Chef for 15 guests home gathering. Starters, biryani, and dessert prep.',
    wage: 2500,
    originalWage: 3000,
    status: 'open',
    rating: 5.0,
    reviewCount: 14,
    location: 'Koramangala, 3rd Block',
    date: 'Saturday 18:00',
    employerName: 'Sengupta Home',
    verified: true,
  ),
  const Job(
    id: 'job-cooking-3',
    title: 'Healthy Meal Prep & Salad Specialist',
    category: 'Cooking',
    description: 'Low-oil keto/high-protein lunch prep for working professionals.',
    wage: 950,
    status: 'open',
    rating: 4.7,
    reviewCount: 22,
    location: 'HSR Layout, Sector 6',
    date: 'Tomorrow 11:00',
    employerName: 'Pai Household',
    verified: true,
  ),

  // --- GARDENING ---
  const Job(
    id: 'job-4',
    title: 'Balcony Garden Tiling & Drainage Fix',
    category: 'Gardening',
    description: 'Laying anti-skid floor tiles in 12x8 ft balcony and installing drainage grate.',
    wage: 1100,
    status: 'completed',
    rating: 5.0,
    reviewCount: 31,
    location: 'Jayanagar, 4th Block',
    date: 'Yesterday',
    employerName: 'Mehta Estate',
    workerName: 'Sunil Sharma',
    verified: true,
  ),
  const Job(
    id: 'job-gardening-2',
    title: 'Lawn Trimming, Weeding & Plant Care',
    category: 'Gardening',
    description: 'Mowing 500 sqft lawn, trimming hedge bushes, and organic fertilisation.',
    wage: 850,
    status: 'open',
    rating: 4.8,
    reviewCount: 16,
    location: 'Sadashivanagar',
    date: 'Tomorrow 09:30',
    employerName: 'Ramaswamy Villa',
    verified: true,
  ),
  const Job(
    id: 'job-gardening-3',
    title: 'Terrace Hydroponic & Potting Setup',
    category: 'Gardening',
    description: 'Setting up drip irrigation line and repotting 25 flowering plants.',
    wage: 1400,
    originalWage: 1600,
    status: 'open',
    rating: 4.9,
    reviewCount: 20,
    location: 'Sarjapur Road',
    date: 'Aug 5, 10:00',
    employerName: 'Joshi Greens',
    verified: true,
  ),

  // --- ELECTRICAL ---
  const Job(
    id: 'job-electrical-1',
    title: 'MCB Tripping Repair & DB Board Rewiring',
    category: 'Electrical',
    description: 'Diagnosing short circuit in master bedroom & replacing faulty 32A MCB switch.',
    wage: 850,
    status: 'open',
    rating: 4.9,
    reviewCount: 38,
    location: 'Indiranagar, Stage 1',
    date: 'Today 15:30',
    employerName: 'Saxena House',
    verified: true,
    urgent: true,
  ),
  const Job(
    id: 'job-electrical-2',
    title: 'Fancy Chandelier & Ceiling Fan Fitting',
    category: 'Electrical',
    description: 'Mounting heavy crystal chandelier and assembling 3 BLDC ceiling fans.',
    wage: 1300,
    originalWage: 1500,
    status: 'open',
    rating: 4.8,
    reviewCount: 25,
    location: 'Koramangala, 6th Block',
    date: 'Tomorrow 14:00',
    employerName: 'Chatterjee Flat',
    verified: true,
  ),
  const Job(
    id: 'job-electrical-3',
    title: 'EV Charger Point & Heavy Line Cable Wiring',
    category: 'Electrical',
    description: 'Installing 15A dedicated socket for electric vehicle charger in parking slot.',
    wage: 1750,
    status: 'open',
    rating: 5.0,
    reviewCount: 11,
    location: 'HSR Layout, Sector 2',
    date: 'Aug 4, 11:30',
    employerName: 'Bhatia Residence',
    verified: true,
  ),
];
